### ISSUE TITLE
Sockets: making messaging real-time

### ISSUE THREAD

**Issue by bonnieli** [clay099/messenger#4]
- Add socket support on the front-end and back-end so that the messages are real-time 
- use this package socket.io for real-time notifications
- Setup socket server on the backend
- Setup client connection (should connect if the user is authed, add some layer of security would be best)
- If you are planning on doing online statuses, we also want an object to keep track of which users are currently connected - for simplicity, you can for now just use an in-memory variable (like a dictionary or object in the back-end - not recommended for scalability, but it works for this project)

**Comment by clay099** [comment]
@tmattmac i just pushed up an update for review. The latest change handles. 
1. update socket auth to use http-only cookies and remove  previous authentication
2. fix bug where moving socket to its custom hook was causing creating a new chat to appear to create multiple chats due to the implementation of the useEffect hook. Moved all socket listeners to their own useEffect hook & added clean up functions to remove listeners
